default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bookdice
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: bookdice

test:
  <<: *default
  database: bookdice

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
